name: lcnn_asv_paper
save_dir: ${hydra:runtime.cwd}/experiments/${name}

# Data
data:
  root_dir: ${hydra:runtime.cwd}/src/datasets/ASVspoof2019
  train:
    batch_size: 8  # Optimized for GPU
    num_workers: 2
    shuffle: true
  val:
    batch_size: 16
    num_workers: 2
    shuffle: false
  test:
    batch_size: 16
    num_workers: 2
    shuffle: false

# Audio processing - following paper specifications
audio:
  sample_rate: 16000
  n_fft: 512
  hop_length: 160  # 10ms at 16kHz
  win_length: 400  # 25ms at 16kHz
  window: hann
  normalized: true
  center: true
  pad_mode: reflect
  power: 2.0  # Power of magnitude spectrogram
  max_audio_length: 64000  # 4 seconds at 16kHz

# Model - exact architecture from paper
model:
  name: lcnn
  in_channels: 1
  num_classes: 2
  dropout: 0.5

# Training - following paper training pattern
training:
  epochs: 15  # Paper uses more epochs
  optimizer:
    name: adam
    lr: 0.0001  # Paper uses 0.0001
    weight_decay: 0.0001
  scheduler:
    name: cosine
    T_max: ${training.epochs}
    eta_min: 0.000001
  grad_clip: 5.0
  early_stopping:
    patience: 15  # More patience as per paper
    min_delta: 0.0001
  loss_type: "cross_entropy"  # Paper uses standard CE loss
  class_weights: [1.0, 1.0]

# Logging
logging:
  comet:
    project: antispoofing-project
    workspace: mshqd
    name: ${name}
    tags: [lcnn, asv, paper]
  log_every_n_steps: 50

# Hydra configuration
hydra:
  run:
    dir: ${save_dir}
  job:
    chdir: true 
